### ISSUE TITLE
disable collapsiblenav in Metrolook?

### ISSUE THREAD

**Issue by lagleki** [paladox/Metrolook#108]
How to do the same for Metrolook:
```
$wgVectorFeatures['collapsiblenav']['global'] = false;
$wgVectorFeatures['collapsiblenav']['user'] = true;
```

More info: http://www.mediawiki.org/wiki/Extension:Vector#CollapsibleNav

**Comment by paladox** [comment]
Hi I have to add support for that. but on my to do list.

**Comment by paladox** [comment]
Hi I will do this now. But may not be released but I will backport this since this is a feature request and should be in all releases.

**Comment by paladox** [comment]
Hi I should be releasing this today.

**Comment by paladox** [comment]
Hi please try 4.0 alpha 3 In master branch. includes the ability to disable collapsiblenav and some other fixes.

**Comment by paladox** [comment]
Hi closing this because I have added it now to metrolook and have released all new releases of metrolook with this feature now. please download metrolook 4.0 alpha 3 for mediawiki 1.26.

**Comment by lagleki** [comment]
mabe hold go to readme to explain how to use it and that it's just now
possible to use it.

2015-05-30 13:49 GMT+03:00 paladox <notifications@github.com>:

**Comment by paladox** [comment]
Oh I have it is at the bottom of the table of settings.

**Comment by paladox** [comment]
You can disable it totally or disable it globaly but allow users to enable it in preference.

**Comment by paladox** [comment]
Hi please update mediawiki 1.26 to latest alpha and I carnt access Special:Version or api.php.

**Comment by paladox** [comment]
Seems like your website is having problems loading or working.
