### ISSUE TITLE
No scrollback after clicking on elements in tables of content

### ISSUE THREAD

**Issue by lagleki** [paladox/Metrolook#109]
Tested on MW 1.26alpha, "Metrolook 4.0 alpha 2 (2a80967) 19:51, 27 May 2015":

Consider you have a very long page with a table of contents like this one:
http://mw.lojban.org/papri/Questions/en

Now you press on an item in that table and then you are moved almost to the end of the page.
Now press "back" button in your browser. 

What is expected:
the scroll position moves back to the table of contents, i.e. to the beginning of the page.

What happens:
the scroll position doesn't move

**Comment by lagleki** [comment]
Are screenshots needed?

**Comment by paladox** [comment]
Oh nope I reproduced it on the site you provided might be browser related or skin. This is based on vector so the problem might happen on vector too.

**Comment by lagleki** [comment]
I remember that at one point this bug didn't happen. Vector doesn't have
this bug.
Do you have a test website with Metrolook installed now where this bug can
be tested independently?

2015-05-29 11:41 GMT+03:00 paladox <notifications@github.com>:

**Comment by paladox** [comment]
Hi I have my website it isent a  test though. http://en.random-wikisaur.tk

**Comment by paladox** [comment]
Do you know how long ago it was working for you because if you do I can look through releases and check code. but may be related to when I switch from old code to new code.

**Comment by paladox** [comment]
But could be to do with because I fixed the header and sidebar.

**Comment by lagleki** [comment]
Indeed, this would be the most likely reason. It could be a year ago. And
by now even Vector differs significantly from what it was at that time.

2015-05-29 11:54 GMT+03:00 paladox <notifications@github.com>:

**Comment by paladox** [comment]
Yes. But I tested on vector and works but they doint have fixed header or sidebar so that may be reason.

**Comment by paladox** [comment]
Hi could you please download the latest update to 4.0 alpha 4 please may have fixed the problem.

**Comment by paladox** [comment]
I have fixed this problem now. I have submitted a patch here https://gerrit.wikimedia.org/r/#/c/227170/

**Comment by paladox** [comment]
This is now fixed. Please use Mediawiki 1.26 for now I will backport the fixes later.
