### ISSUE TITLE
GUI overlay glitch in upper toolbar

### ISSUE THREAD

**Issue by lagleki** [paladox/Metrolook#117]
Open https://mw.lojban.org/papri/Special:RecentChanges You get:
![1](https://cloud.githubusercontent.com/assets/2412817/10024471/074d6e12-6160-11e5-9e3b-3c400431e8e1.png)

Now scroll it down:
![2](https://cloud.githubusercontent.com/assets/2412817/10024472/0773d138-6160-11e5-8adc-b227e81e9306.png)

You can see that "Help" link is above the toolbar (in the upper right part of the screenshot).

**Comment by paladox** [comment]
I think it is to do with z-index. I will test a fix and upload it if it works. Thanks for reporting this.

**Comment by paladox** [comment]
Please test from latest master branch.

**Comment by paladox** [comment]
Please re open if it dosent fix the issue.
