### ISSUE TITLE
hamburgerIcon

### ISSUE THREAD

**Issue by paladox** [paladox/Metrolook#84]
Hi just noticed hamburgerIcon in pidgiwiki seems to be hidden in code I managed to get it to work but it should be next to logo on top bar. Who would like this in metrolook. It can hide and show the sidebar. useful for people.

**Comment by immewnity** [comment]
I will be unveiling the mobile adaptation of PidgiWiki on February 2 as part of the site's 5th birthday celebration. I will see if I can adapt this to the code that is here after that happens.

**Comment by paladox2015** [comment]
Ok thanks. I am updating the code to match the changes in vector but they wont be majour changes. I will also be adding svg version of the bullet including adding a circle. I have try to do what you done by letting you hide the sidebar but moving the sitename a bit will cause the content to go out of screen.
