### ISSUE TITLE
Testing new release in test branch

### ISSUE THREAD

**Issue by paladox** [paladox/Metrolook#92]
Hi could someone test the new release on there website and reports bugs or fix the prolem if you know how to please. main focus is the mobile desgn.

**Comment by immewnity** [comment]
It's on http://www.pidgi.net/metrolooktest/ now.

**Comment by paladox** [comment]
Thanks for doing that. I am trying to fix all desgn problems that have to do with mobile desgn since there are still some problems and if people visit the website through android they could give feedback that it doesent work on android. But it is almost ready to be released.

**Comment by paladox** [comment]
Already released now.
