### ISSUE TITLE
Full logo support in beta 16

### ISSUE THREAD

**Issue by paladox** [paladox/Metrolook#93]
Full support for logo has been added in beta 16. Settings were also split to allow full support for logo.

**Comment by immewnity** [comment]
I haven't checked to see the implementation, but I'm testing a modified version of the original skin using a full logo. It's viewable at http://www.pidgi.net/testing/ctawiki/ .

**Comment by paladox** [comment]
Ok it is similar to how you have except I have also the sitename at the top.

**Comment by lagleki** [comment]
hm, it'd be nice to be able to disable the sitename optionally. seems to be
easy to implement.

2015-02-26 10:29 GMT+03:00 paladox <notifications@github.com>:

**Comment by paladox** [comment]
Hi i also did that too i changed alot of settings and how they worked i also clean up alot of code.

**Comment by paladox** [comment]
I may release the update soon since i have added a setting to disable mobile view if you think it is unstable. and be able to give feedback. i will then back port the changes to the other releases.
